spring:
  data:
    mongodb:
      host: localhost
      port: 28028
      database: customer
      username: username
      password: password
      authentication-database: admin
server:
  port: 8081