spring:
  datasource:
    url: jdbc:postgresql://localhost:9119/order
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

application:
  config:
    customer-url: http://localhost:8081/api/v1/customers
    product-url: http://localhost:8082/api/v1/products
    payment-url: http://localhost:8084/api/v1/payments

